### ISSUE TITLE
I[E.showMethod] is not a function error with bootstrap 4.2.1

### ISSUE THREAD

**Issue by Reegan01** [CodeSeven/toastr#602]
![desktop screenshot](https://user-images.githubusercontent.com/7336944/50852001-61ed0b80-13a4-11e9-8b8c-3ac8d45eac0b.png)

Got that issue while working with bootstrap 4.2.1.  If it due to jQuery slim usage, then how to work with bootstrap?

**Comment by samuelallan72** [comment]
I successfully resolved this error by using the full jQuery library instead of the slim edition. You should be able to install/require/include the jQuery edition you want - don't have to stick with the slim edition.

**Comment by Thecave3** [comment]
This issue is still open, but the @swalladge fix solved it.

**Comment by cherradix** [comment]
Thanks its work using uncompressed jquery library 
i use this :

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
