### ISSUE TITLE
Toastr not working with Jquery 3.3.1

### ISSUE THREAD

**Issue by aiksu** [CodeSeven/toastr#594]
While using jquery 3.3.1 from official CDN and the latest toastr cdn
```
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
...
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
```
this error appears:
```
Uncaught TypeError: I[E.showMethod] is not a function
    at r (toastr.js:474)
    at g (toastr.js:474)
    at Object.a [as warning] (toastr.js:474)
    at HTMLInputElement.<anonymous> ((index):407)
    at HTMLInputElement.dispatch (jquery-3.3.1.slim.min.js:2)
    at HTMLInputElement.v.handle (jquery-3.3.1.slim.min.js:2)
```

The solution is to change Jquery back to 3.2.1. Works for me.

**Comment by Abourass** [comment]
Have you tried using the non-slim version?

**Comment by Abourass** [comment]
Can confirm it works **with** the newest version. You need to link the non slim version, the slim version is missing some features. Use the jquery.min.js that is newest and it works as expected.

**Comment by johannes-schuetze** [comment]
I have an comment on this too. In my bower.json file i am including: 
`"toastr": "^2.1.3"`
 and it installs it, however because the build is dependent on Jquery 3.2.1 it throws an exception for incompatible version:
`toastr#2.1.3 -> jquery#3.2.1 incompatible with >=1.6.3 <3`
I check the repo and you guys supposedly fixed this in commit: `113a6f6f995e39d965de3947edf8021ed2d5fda2`
Is there any explanation for this?

**Comment by johannes-schuetze** [comment]
Found a work around in the other repo (maybe i jumped around to much and lost my head and this issue only persists in the other repo)  issue thread:
`https://github.com/johnpapa/toastr-bower/issues/10`
Just had to change the bower.json entry to:
`"toastr": "toastr#113a6f6"`

**Comment by BeamBrother** [comment]
I also encountered this problem. I finally found you after looking for it all morning. It is really uncomfortable when this version is incompatible.
