### ISSUE TITLE
toastr[type] is not a function

### ISSUE THREAD

**Issue by Rst0000** [CodeSeven/toastr#483]
Hi, I'm trying to call toastr like this:

`var showToastr = function (msg, type) {
     return toastr[type](msg);
};

var type = 'info';
var message = 'Test';

showToastr(message, type);`

and it works but console prints error:
`Uncaught TypeError: toastr[type] is not a function`

Can you give me an advice how to deal with that? I'd like to avoid any errors in console.

**Comment by TimFerrell** [comment]
In what order are you loading toastr, and executing this call?

**Comment by Rst0000** [comment]
First I'm loading jquery, foundation, toastr and then my app.js. In app.js I have 3 functions:

`var showToastr = function (msg, type) {`
`    return toastr[type](msg);`
`};`

`var toastrConfig = function () {`
`    toastr.options = appOptions.toastr;`
`};`

`var showNotifications = function () {`
`   $('.notification').each(function () {`
`       var type = $(this).data('type');`
`       var message = $(this).html();`

`      showToastr(message, type);`
`    });`
`};`

Belom I call functions in order:
toastrConfig();
showNotifications();

`.notification` are returned by backend

and console point error to:
`    return toastr[type](msg);`

**Comment by scilganon** [comment]
@Rst0000 if you want to avoid errors in console, just use [try-catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) :D

---

as a web-developer, you can use developer-mode for any browser (e.g.: [dev-tools for chrome](https://developer.chrome.com/devtools#debugging-javascript))
and better follow next steps to identify your problem: mark line with an error as line for debug ([breakpoints](https://developers.google.com/web/tools/chrome-devtools/javascript/add-breakpoints)) and check value of toastr variable, also you can use console/panels to check соntent of that variable

**Comment by rodrigogs** [comment]
In my case it happened due to jQuery slim.

**Comment by rbryan21** [comment]
@rodrigogs Thank you so much, I had the same problem! You saved me from a minor mental breakdown my friend.

**Comment by liujundezhanghao** [comment]
@rodrigogs  Thank you,you the best

**Comment by Reegan01** [comment]
If it is due to jQuery slim then how to work with bootstrap 4.2.1? Because Bootstrap using JQuery slim version.

**Comment by Gradius30** [comment]
Hello guys. So the same happens to me even with jQuery 3.3.1 / toastr 2.1.4

```
let type = 'info'
let msg = 'message';
toastr[type](msg);
```

```
TypeError: toastr[type] is not a function...
```

Anybody also experiencing this?
